### ISSUE TITLE
Newest arraybuffer does not work with this library

### ISSUE THREAD

**Issue by justinwoo** [adkelley/purescript-webaudio#7]
Do you still use this library? I could help look at this sometime.

**Comment by rskew** [comment]
@justinwoo I've got an update for this https://github.com/adkelley/purescript-webaudio/pull/8
@mlang if you're still using this library I could submit a PR to your fork as well

**Comment by adkelley** [comment]
I'm going to get this library updated and published to 0.13.3 over the next few days.  Standby

**Comment by adkelley** [comment]
Support for purescript@0.13.3 successfully submitted.  Thanks, @rskew, and @mlang for your PRs.
